name: Building Fluent Operator image

on:
  push:
    branches:
      - 'master'
      - 'ISSUE-*'
    tags:
      - 'v*'
    paths:
      - ".github/workflows/build-op-image.yaml"
      - "apis/**"
      - "cmd/fluent-manager/**"
      - "controllers/**"
      - "hack/**"
      - "manifests/setup/setup.yaml"
      - "pkg/fluentd/router/**"
      - "pkg/fluentd/operator/**"
      - "pkg/fluentd/utils/**"
      - "Makefile"

  pull_request:
    branches:
      - 'master'

env:
  REGISTRY_REPO: 'sarathchandra24'
  DOCKER_IMAGE: 'fluent-operator'
  GITHUB_IMAGE: "${{ github.repository }}/fluent-operator"

jobs:
  operator-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for Fluent Operator
    outputs:
      IMG_VERSION: ${{ steps.image-metadata.outputs.version }}
      IMG_NAME: ${{ steps.image-metadata.outputs.tags }}[0]
      OPERATOR_DOCKER_IMG: "${{ env.REGISTRY_REPO }}/${{ env.DOCKER_IMAGE }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: docker metadata
        id: image-metadata
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ env.GITHUB_IMAGE }}"
          tags: |
            raw,latest
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-manager/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}

  scan-operator-image:
    name: Scan Docker Image
    needs: 
      - operator-build
    uses: ./.github/workflows/call-scan-images.yaml
    with:
      source_image: "${{ needs.operator-build.outputs.IMG_NAME }}"
      source_registry: ghcr.io
      platforms: '["linux/arm64", "linux/amd64"]'
    secrets:
      registry_username: ${{ github.actor_id }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  release-image-to-docker-hub:
    if: always()
    name: Release Image to Docker Hub
    uses: ./.github/workflows/call-clone-images.yaml
    needs: 
      - operator-build
      - scan-operator-image
    with:
      source_image: "${{ needs.operator-build.outputs.IMG_NAME }}"
      source_registry: ghcr.io
      target_image: ${{ needs.operator-build.outputs.OPERATOR_DOCKER_IMG }}
      target_registry: docker.io
      platforms: "['linux/arm64', 'linux/amd64']"
    secrets:
      source_registry_username:  ${{ github.actor_id }}
      source_registry_token: ${{ secrets.GITHUB_TOKEN }}
      target_registry_username: ${{ secrets.REGISTRY_USER }}
      target_registry_token: ${{ secrets.REGISTRY_PASSWORD }}
