name: Building Fluent Operator image

on:
  push:
    branches:
      - 'master'
      - 'ISSUE-*'
    tags:
      - 'v*'
    paths:
      - ".github/workflows/build-op-image.yaml"
      - "apis/**"
      - "cmd/fluent-manager/**"
      - "controllers/**"
      - "hack/**"
      - "manifests/setup/setup.yaml"
      - "pkg/fluentd/router/**"
      - "pkg/fluentd/operator/**"
      - "pkg/fluentd/utils/**"
      - "Makefile"

  pull_request:
    branches:
      - 'master'

env:
  DOCKER_REPO: 'sarathchandra24'
  DOCKER_IMAGE: 'fluent-operator'
  GITHUB_IMAGE: "${{ github.repository }}/fluent-operator"

jobs:
  build-image-metadata:
    runs-on: ubuntu-latest
    name: Build Image Metadata
    outputs:
      FULL_IMG_NAME: ${{ steps.set-outputs.outputs.FULL_IMAGE_NAME }}
      IMG_NAME: ${{ steps.set-outputs.outputs.IMAGE_NAME }}
      DOCKER_IMG_NAME: ${{ steps.set-outputs.outputs.DOCKER_IMG_NAME }}
      version: ${{ steps.image-metadata.outputs.version }}
      tags: ${{ steps.image-metadata.outputs.tags }}
      labels: ${{ steps.image-metadata.outputs.labels }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
            
      - name: docker metadata
        id: image-metadata
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ env.GITHUB_IMAGE }}"
          tags: |
            raw,latest
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set outputs
        id: set-outputs
        run: |
          echo "FULL_IMAGE_NAME=$(echo '${{ steps.image-metadata.outputs.json }}' | jq '.tags[0]')" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${{ env.GITHUB_IMAGE }}" >> $GITHUB_OUTPUT
          echo "DOCKER_IMG_NAME=${{env.DOCKER_REPO}}/${{ env.DOCKER_IMAGE }}" >> $GITHUB_OUTPUT

          echo "FULL_IMAGE_NAME=$(echo '${{ steps.image-metadata.outputs.json }}'
          echo "IMAGE_NAME=${{ env.GITHUB_IMAGE }}"
          echo "DOCKER_IMG_NAME=${{env.DOCKER_REPO}}/${{ env.DOCKER_IMAGE }}"


  operator-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for Fluent Operator
    needs: 
      - build-image-metadata
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor_id }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-manager/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ needs.build-image-metadata.outputs.tags }}
          labels: ${{ needs.build-image-metadata.outputs.labels }}

  scan-operator-image:
    name: Scan Docker Image
    needs: 
      - operator-build
      - build-image-metadata
    uses: ./.github/workflows/call-scan-images.yaml
    with:
      source_image: "${{ needs.build-image-metadata.outputs.FULL_IMG_NAME }}"
      source_registry: ghcr.io
      platforms: '["linux/arm64", "linux/amd64"]'
    secrets:
      registry_username: ${{ github.actor_id }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  release-image-to-docker-hub:
    if: always()
    name: Release Image to Docker Hub
    uses: ./.github/workflows/call-clone-images.yaml
    needs: 
      - operator-build
      - scan-operator-image
      - build-image-metadata
    with:
      source_image: "${{ needs.build-image-metadata.outputs.FULL_IMG_NAME }}"
      source_registry: ghcr.io
      target_image: ${{ needs.build-image-metadata.outputs.DOCKER_IMG_NAME }}
      target_registry: docker.io
      platforms: "['linux/arm64', 'linux/amd64']"
    secrets:
      source_registry_username:  ${{ github.actor_id }}
      source_registry_token: ${{ secrets.GITHUB_TOKEN }}
      target_registry_username: ${{ secrets.REGISTRY_USER }}
      target_registry_token: ${{ secrets.REGISTRY_PASSWORD }}
