name: Building Fluent Operator image

on:
  push:
    branches:
      - 'master'
      - 'ISSUE-*'
    tags:
      - 'v*'
    paths:
      - ".github/workflows/build-op-image.yaml"
      - "apis/**"
      - "cmd/fluent-manager/**"
      - "controllers/**"
      - "hack/**"
      - "manifests/setup/setup.yaml"
      - "pkg/fluentd/router/**"
      - "pkg/fluentd/operator/**"
      - "pkg/fluentd/utils/**"
      - "Makefile"

  pull_request:
    branches:
      - 'master'

env:
  REGISTRY_REPO: 'sarathchandra24'
  DOCKER_IMAGE: 'fluent-operator'
  GITHUB_IMAGE: "${{ github.repository }}/fluent-operator"


jobs:
  operator-buils:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for Fluent Operator
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: docker metadata
        id: image-metadata
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ env.GITHUB_IMAGE }}"
          tags: |
            raw,latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-manager/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}
